### ISSUE TITLE
license for PilferShush

### ISSUE THREAD

**Issue by seandiggity** [kaputnikGo/PilferShush#1]
What is the license status of this project? We're working on some ultrasonic tracking for Yale Privacy Lab and would love to start hacking on this code (potentially for an Android app that we would package for F-Droid), but we want to make sure it's available under a Free and Open-Source License.

**Comment by kaputnikGo** [comment]
Hi, i always make stuff here available under https://creativecommons.org/licenses/by-nc-sa/4.0/ and its equivalents. However the file Goertzel.java uses an implementation of the algorithm found here:
Banks, Kevin. “The Goertzel Algorithm.” Embedded Systems Programming15, 9 (2002): 34–42

not sure what the status is on that one.
I am interested in this area in general so feel free to keep me informed, especially if you produce an Fdroid app, or if I can help in any way.

**Comment by seandiggity** [comment]
Wonderful!  Please drop me a line via e-mail so I have a more direct way to contact you.

CC licenses are great and ShareAlike is even better, but the Non-Commercial clause may introduce issues because it can't be mixed with the GPL.  But we'll talk through that down the line.  Thanks.

**Comment by seandiggity** [comment]
We've now got PilferShush available here under the GNU GPLv3: https://github.com/YalePrivacyLab/PilferShush_prod
